name: AbstractCooldown
main: ru.abstractcoder.abstractcooldown.AbstractCooldownPlugin
author: AbstractCoder, Rozipp
version: 1.1
website: http://abstractcoder.ru
description: Многофункциональный плагин на кулдауны для команд.
softdepend: [Vault]
commands:
  abstractcooldown:
    aliases: [acd]